name: Destroy terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Destroy resources?'
        type: choice
        options:
        - yes_sure
        - God_forbid

jobs:
  destroy:
    name: Destroy
    if: ${{ github.event.inputs.action == 'yes_sure' }}
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Get app version
      run: |
        version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "App version: $version"
        echo "VERSION=$version" >> $GITHUB_ENV
        
    - name: Destroy resource
      run: |
        cd terraform
        terraform fmt -recursive
        terraform init
        terraform destroy -var='aws_region=${{ vars.AWS_REGION }}' -var='app_version=${{ env.VERSION }}' -var="projectname=${{ vars.PROJECT }}" -var="cluster_name=${{ vars.CLUSTER }}" -var="buckets3=${{ vars.BUCKET }}" -var="access_secret_key=${{ secrets.AWS_ACCESS_SECRET_KEY }}" -var="cognito_jwk_uri=${{ secrets.COGNITO_JWK_URI }}" -var="mongodb_url=${{ secrets.MONGODB_URL }}" -var="cognito_user_pool=${{ secrets.COGNITO_USER_POOL }}" -var="cognito_client_id=${{ secrets.COGNITO_CLIENT_ID }}" -var="cognito_secret=${{ secrets.COGNITO_SECRET }}" -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" --auto-approve